// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bahanmenu.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	bahanmenu.proto

It has these top-level messages:
	AddBahanMenuReq
	ReadBahanMenuByNamaBahanMenuReq
	ReadBahanMenuByNamaBahanMenuResp
	ReadBahanMenuResp
	UpdateBahanMenurReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddBahanMenuReq struct {
	Namabahan string `protobuf:"bytes,1,opt,name=namabahan" json:"namabahan,omitempty"`
	Quantity  int32  `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	Status    int32  `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Createdby string `protobuf:"bytes,4,opt,name=createdby" json:"createdby,omitempty"`
}

func (m *AddBahanMenuReq) Reset()                    { *m = AddBahanMenuReq{} }
func (m *AddBahanMenuReq) String() string            { return proto.CompactTextString(m) }
func (*AddBahanMenuReq) ProtoMessage()               {}
func (*AddBahanMenuReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddBahanMenuReq) GetNamabahan() string {
	if m != nil {
		return m.Namabahan
	}
	return ""
}

func (m *AddBahanMenuReq) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *AddBahanMenuReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddBahanMenuReq) GetCreatedby() string {
	if m != nil {
		return m.Createdby
	}
	return ""
}

type ReadBahanMenuByNamaBahanMenuReq struct {
	Namabahan string `protobuf:"bytes,1,opt,name=namabahan" json:"namabahan,omitempty"`
}

func (m *ReadBahanMenuByNamaBahanMenuReq) Reset()                    { *m = ReadBahanMenuByNamaBahanMenuReq{} }
func (m *ReadBahanMenuByNamaBahanMenuReq) String() string            { return proto.CompactTextString(m) }
func (*ReadBahanMenuByNamaBahanMenuReq) ProtoMessage()               {}
func (*ReadBahanMenuByNamaBahanMenuReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadBahanMenuByNamaBahanMenuReq) GetNamabahan() string {
	if m != nil {
		return m.Namabahan
	}
	return ""
}

type ReadBahanMenuByNamaBahanMenuResp struct {
	Idbahan   int32  `protobuf:"varint,1,opt,name=idbahan" json:"idbahan,omitempty"`
	Namabahan string `protobuf:"bytes,2,opt,name=namabahan" json:"namabahan,omitempty"`
	Quantity  int32  `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	Status    int32  `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	Createdby string `protobuf:"bytes,5,opt,name=createdby" json:"createdby,omitempty"`
}

func (m *ReadBahanMenuByNamaBahanMenuResp) Reset()         { *m = ReadBahanMenuByNamaBahanMenuResp{} }
func (m *ReadBahanMenuByNamaBahanMenuResp) String() string { return proto.CompactTextString(m) }
func (*ReadBahanMenuByNamaBahanMenuResp) ProtoMessage()    {}
func (*ReadBahanMenuByNamaBahanMenuResp) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2}
}

func (m *ReadBahanMenuByNamaBahanMenuResp) GetIdbahan() int32 {
	if m != nil {
		return m.Idbahan
	}
	return 0
}

func (m *ReadBahanMenuByNamaBahanMenuResp) GetNamabahan() string {
	if m != nil {
		return m.Namabahan
	}
	return ""
}

func (m *ReadBahanMenuByNamaBahanMenuResp) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *ReadBahanMenuByNamaBahanMenuResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadBahanMenuByNamaBahanMenuResp) GetCreatedby() string {
	if m != nil {
		return m.Createdby
	}
	return ""
}

type ReadBahanMenuResp struct {
	AllBahanMenu []*ReadBahanMenuByNamaBahanMenuResp `protobuf:"bytes,1,rep,name=allBahanMenu" json:"allBahanMenu,omitempty"`
}

func (m *ReadBahanMenuResp) Reset()                    { *m = ReadBahanMenuResp{} }
func (m *ReadBahanMenuResp) String() string            { return proto.CompactTextString(m) }
func (*ReadBahanMenuResp) ProtoMessage()               {}
func (*ReadBahanMenuResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadBahanMenuResp) GetAllBahanMenu() []*ReadBahanMenuByNamaBahanMenuResp {
	if m != nil {
		return m.AllBahanMenu
	}
	return nil
}

type UpdateBahanMenurReq struct {
	Idbahan   int32  `protobuf:"varint,1,opt,name=idbahan" json:"idbahan,omitempty"`
	Namabahan string `protobuf:"bytes,2,opt,name=namabahan" json:"namabahan,omitempty"`
	Quantity  int32  `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	Status    int32  `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	UpdateBy  string `protobuf:"bytes,5,opt,name=updateBy" json:"updateBy,omitempty"`
}

func (m *UpdateBahanMenurReq) Reset()                    { *m = UpdateBahanMenurReq{} }
func (m *UpdateBahanMenurReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateBahanMenurReq) ProtoMessage()               {}
func (*UpdateBahanMenurReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateBahanMenurReq) GetIdbahan() int32 {
	if m != nil {
		return m.Idbahan
	}
	return 0
}

func (m *UpdateBahanMenurReq) GetNamabahan() string {
	if m != nil {
		return m.Namabahan
	}
	return ""
}

func (m *UpdateBahanMenurReq) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *UpdateBahanMenurReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateBahanMenurReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func init() {
	proto.RegisterType((*AddBahanMenuReq)(nil), "grpc.AddBahanMenuReq")
	proto.RegisterType((*ReadBahanMenuByNamaBahanMenuReq)(nil), "grpc.ReadBahanMenuByNamaBahanMenuReq")
	proto.RegisterType((*ReadBahanMenuByNamaBahanMenuResp)(nil), "grpc.ReadBahanMenuByNamaBahanMenuResp")
	proto.RegisterType((*ReadBahanMenuResp)(nil), "grpc.ReadBahanMenuResp")
	proto.RegisterType((*UpdateBahanMenurReq)(nil), "grpc.UpdateBahanMenurReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for BahanMenuService service

type BahanMenuServiceClient interface {
	AddBahanMenu(ctx context.Context, in *AddBahanMenuReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadBahanMenuByNamaBahanMenu(ctx context.Context, in *ReadBahanMenuByNamaBahanMenuReq, opts ...grpc1.CallOption) (*ReadBahanMenuByNamaBahanMenuResp, error)
	ReadBahanMenu(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadBahanMenuResp, error)
	UpdateBahanMenu(ctx context.Context, in *UpdateBahanMenurReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type bahanMenuServiceClient struct {
	cc *grpc1.ClientConn
}

func NewBahanMenuServiceClient(cc *grpc1.ClientConn) BahanMenuServiceClient {
	return &bahanMenuServiceClient{cc}
}

func (c *bahanMenuServiceClient) AddBahanMenu(ctx context.Context, in *AddBahanMenuReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.BahanMenuService/AddBahanMenu", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bahanMenuServiceClient) ReadBahanMenuByNamaBahanMenu(ctx context.Context, in *ReadBahanMenuByNamaBahanMenuReq, opts ...grpc1.CallOption) (*ReadBahanMenuByNamaBahanMenuResp, error) {
	out := new(ReadBahanMenuByNamaBahanMenuResp)
	err := grpc1.Invoke(ctx, "/grpc.BahanMenuService/ReadBahanMenuByNamaBahanMenu", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bahanMenuServiceClient) ReadBahanMenu(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadBahanMenuResp, error) {
	out := new(ReadBahanMenuResp)
	err := grpc1.Invoke(ctx, "/grpc.BahanMenuService/ReadBahanMenu", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bahanMenuServiceClient) UpdateBahanMenu(ctx context.Context, in *UpdateBahanMenurReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.BahanMenuService/UpdateBahanMenu", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BahanMenuService service

type BahanMenuServiceServer interface {
	AddBahanMenu(context.Context, *AddBahanMenuReq) (*google_protobuf.Empty, error)
	ReadBahanMenuByNamaBahanMenu(context.Context, *ReadBahanMenuByNamaBahanMenuReq) (*ReadBahanMenuByNamaBahanMenuResp, error)
	ReadBahanMenu(context.Context, *google_protobuf.Empty) (*ReadBahanMenuResp, error)
	UpdateBahanMenu(context.Context, *UpdateBahanMenurReq) (*google_protobuf.Empty, error)
}

func RegisterBahanMenuServiceServer(s *grpc1.Server, srv BahanMenuServiceServer) {
	s.RegisterService(&_BahanMenuService_serviceDesc, srv)
}

func _BahanMenuService_AddBahanMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBahanMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BahanMenuServiceServer).AddBahanMenu(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BahanMenuService/AddBahanMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BahanMenuServiceServer).AddBahanMenu(ctx, req.(*AddBahanMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BahanMenuService_ReadBahanMenuByNamaBahanMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBahanMenuByNamaBahanMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BahanMenuServiceServer).ReadBahanMenuByNamaBahanMenu(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BahanMenuService/ReadBahanMenuByNamaBahanMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BahanMenuServiceServer).ReadBahanMenuByNamaBahanMenu(ctx, req.(*ReadBahanMenuByNamaBahanMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BahanMenuService_ReadBahanMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BahanMenuServiceServer).ReadBahanMenu(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BahanMenuService/ReadBahanMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BahanMenuServiceServer).ReadBahanMenu(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BahanMenuService_UpdateBahanMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBahanMenurReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BahanMenuServiceServer).UpdateBahanMenu(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BahanMenuService/UpdateBahanMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BahanMenuServiceServer).UpdateBahanMenu(ctx, req.(*UpdateBahanMenurReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BahanMenuService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.BahanMenuService",
	HandlerType: (*BahanMenuServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddBahanMenu",
			Handler:    _BahanMenuService_AddBahanMenu_Handler,
		},
		{
			MethodName: "ReadBahanMenuByNamaBahanMenu",
			Handler:    _BahanMenuService_ReadBahanMenuByNamaBahanMenu_Handler,
		},
		{
			MethodName: "ReadBahanMenu",
			Handler:    _BahanMenuService_ReadBahanMenu_Handler,
		},
		{
			MethodName: "UpdateBahanMenu",
			Handler:    _BahanMenuService_UpdateBahanMenu_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "bahanmenu.proto",
}

func init() { proto.RegisterFile("bahanmenu.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0xcb, 0x4e, 0xc2, 0x40,
	0x14, 0x65, 0x78, 0x09, 0x57, 0x0c, 0x7a, 0x8d, 0x58, 0x2b, 0x89, 0x4d, 0x13, 0x0d, 0xab, 0x92,
	0xe0, 0x07, 0x10, 0x49, 0x74, 0x61, 0xa2, 0x8b, 0x1a, 0xd7, 0xe6, 0x96, 0x8e, 0x48, 0x42, 0x1f,
	0x94, 0xa9, 0x49, 0x97, 0x7e, 0x88, 0x7f, 0xe0, 0xc7, 0xf8, 0x49, 0xa6, 0x2d, 0x0c, 0x96, 0x50,
	0xec, 0xca, 0xe5, 0x3d, 0x73, 0xe7, 0xe4, 0x9c, 0x73, 0x0f, 0xb4, 0x2d, 0x7a, 0x23, 0xd7, 0xe1,
	0x6e, 0x68, 0xf8, 0x81, 0x27, 0x3c, 0xac, 0x4e, 0x02, 0x7f, 0xac, 0x9e, 0x4f, 0x3c, 0x6f, 0x32,
	0xe3, 0xfd, 0x04, 0xb3, 0xc2, 0xd7, 0x3e, 0x77, 0x7c, 0x11, 0xa5, 0x2b, 0xfa, 0x07, 0x83, 0xf6,
	0x8d, 0x6d, 0x8f, 0xe2, 0x9f, 0x0f, 0xdc, 0x0d, 0x4d, 0x3e, 0xc7, 0x2e, 0x34, 0x5d, 0x72, 0x28,
	0x61, 0x53, 0x98, 0xc6, 0x7a, 0x4d, 0x73, 0x0d, 0xa0, 0x0a, 0x8d, 0x79, 0x48, 0xae, 0x98, 0x8a,
	0x48, 0x29, 0x6b, 0xac, 0x57, 0x33, 0xe5, 0x8c, 0x1d, 0xa8, 0x2f, 0x04, 0x89, 0x70, 0xa1, 0x54,
	0x92, 0x97, 0xe5, 0x14, 0x33, 0x8e, 0x03, 0x4e, 0x82, 0xdb, 0x56, 0xa4, 0x54, 0x53, 0x46, 0x09,
	0xe8, 0x43, 0xb8, 0x30, 0x39, 0xad, 0x35, 0x8c, 0xa2, 0x47, 0x72, 0xa8, 0xb8, 0x24, 0xfd, 0x8b,
	0x81, 0xb6, 0x9b, 0x61, 0xe1, 0xa3, 0x02, 0x7b, 0x53, 0x7b, 0x4d, 0x50, 0x33, 0x57, 0x63, 0x96,
	0xbc, 0xbc, 0xcb, 0x6f, 0x25, 0xd7, 0x6f, 0x35, 0xdf, 0x6f, 0x6d, 0xd3, 0xef, 0x0b, 0x1c, 0x65,
	0xd4, 0x26, 0xf2, 0xee, 0xa1, 0x45, 0xb3, 0x99, 0xc4, 0x14, 0xa6, 0x55, 0x7a, 0xfb, 0x83, 0x2b,
	0x23, 0x3e, 0xa1, 0xf1, 0x97, 0x39, 0x33, 0xf3, 0x57, 0xff, 0x64, 0x70, 0xfc, 0xec, 0xdb, 0x24,
	0xb8, 0xc4, 0x82, 0x38, 0xc5, 0xff, 0x8c, 0x40, 0x85, 0x46, 0x98, 0x4a, 0x58, 0x25, 0x20, 0xe7,
	0xc1, 0x77, 0x19, 0x0e, 0xa5, 0xb2, 0x27, 0x1e, 0xbc, 0x4f, 0xc7, 0x1c, 0x87, 0xd0, 0xfa, 0x5d,
	0x44, 0x3c, 0x49, 0xad, 0x6f, 0x94, 0x53, 0xed, 0x18, 0x69, 0x9d, 0x8d, 0x55, 0x9d, 0x8d, 0xdb,
	0xb8, 0xce, 0x7a, 0x09, 0x3d, 0xe8, 0xee, 0xca, 0x09, 0x2f, 0x8b, 0x64, 0x39, 0x57, 0x0b, 0x46,
	0xae, 0x97, 0x70, 0x04, 0x07, 0x99, 0x2d, 0xcc, 0xd1, 0xa6, 0x9e, 0x6e, 0xa1, 0x5c, 0x72, 0xdc,
	0x41, 0x7b, 0xe3, 0x52, 0x78, 0x96, 0x6e, 0x6f, 0x39, 0x60, 0xbe, 0x79, 0xab, 0x9e, 0x20, 0xd7,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x50, 0x4e, 0xd0, 0x8b, 0x04, 0x04, 0x00, 0x00,
}
